package com.groupdocs.markdown.examples;

import java.io.File;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Runs the generated GroupDocs.Total examples. Generated by docs-to-code-examples;
 * edit the documentation, not this file.
 */
public final class Main {

    /** An example's entry point; run() may throw, so Runnable will not do. */
    @FunctionalInterface
    interface Example {
        void run() throws Exception;
    }

    private static final Map<String, Example> EXAMPLES = new LinkedHashMap<>();

    static {
        EXAMPLES.put("QsWordToMd", com.groupdocs.markdown.examples.gettingstarted.quickstartguide.QsWordToMd::run);
        EXAMPLES.put("QsPdfWithImages", com.groupdocs.markdown.examples.gettingstarted.quickstartguide.QsPdfWithImages::run);
        EXAMPLES.put("QsExcelOptions", com.groupdocs.markdown.examples.gettingstarted.quickstartguide.QsExcelOptions::run);
        EXAMPLES.put("LicenseStaticFile", com.groupdocs.markdown.examples.gettingstarted.licensingandsubscription.LicenseStaticFile::run);
        EXAMPLES.put("LicenseInstanceFile", com.groupdocs.markdown.examples.gettingstarted.licensingandsubscription.LicenseInstanceFile::run);
        EXAMPLES.put("LicenseStaticStream", com.groupdocs.markdown.examples.gettingstarted.licensingandsubscription.LicenseStaticStream::run);
        EXAMPLES.put("LicenseInstanceStream", com.groupdocs.markdown.examples.gettingstarted.licensingandsubscription.LicenseInstanceStream::run);
        EXAMPLES.put("LicenseMetered", com.groupdocs.markdown.examples.gettingstarted.licensingandsubscription.LicenseMetered::run);
        EXAMPLES.put("LoadDiskStatic", com.groupdocs.markdown.examples.developerguide.advancedusage.loading.loadfromalocaldisk.LoadDiskStatic::run);
        EXAMPLES.put("LoadDiskInstance", com.groupdocs.markdown.examples.developerguide.advancedusage.loading.loadfromalocaldisk.LoadDiskInstance::run);
        EXAMPLES.put("ExportPdfStatic", com.groupdocs.markdown.examples.developerguide.basicusage.convert.exportpdf.ExportPdfStatic::run);
        EXAMPLES.put("ExportPdfInstance", com.groupdocs.markdown.examples.developerguide.basicusage.convert.exportpdf.ExportPdfInstance::run);
        EXAMPLES.put("LoadStreamExample", com.groupdocs.markdown.examples.developerguide.advancedusage.loading.loadfromastream.LoadStreamExample::run);
        EXAMPLES.put("LoadStreamOptions", com.groupdocs.markdown.examples.developerguide.advancedusage.loading.loadfromastream.LoadStreamOptions::run);
        EXAMPLES.put("ExportWordStatic", com.groupdocs.markdown.examples.developerguide.basicusage.convert.exportwordprocessing.ExportWordStatic::run);
        EXAMPLES.put("ExportWordInstance", com.groupdocs.markdown.examples.developerguide.basicusage.convert.exportwordprocessing.ExportWordInstance::run);
        EXAMPLES.put("GetInfoStatic", com.groupdocs.markdown.examples.developerguide.basicusage.getdocumentinfo.GetInfoStatic::run);
        EXAMPLES.put("GetInfoInstance", com.groupdocs.markdown.examples.developerguide.basicusage.getdocumentinfo.GetInfoInstance::run);
        EXAMPLES.put("LoadSpecificFormat", com.groupdocs.markdown.examples.developerguide.advancedusage.loading.loadafileofaspecificformat.LoadSpecificFormat::run);
        EXAMPLES.put("LoadSupportedFormats", com.groupdocs.markdown.examples.developerguide.advancedusage.loading.loadafileofaspecificformat.LoadSupportedFormats::run);
        EXAMPLES.put("ExportSpreadsheetStatic", com.groupdocs.markdown.examples.developerguide.basicusage.convert.exportspreadsheet.ExportSpreadsheetStatic::run);
        EXAMPLES.put("ExportSpreadsheetInstance", com.groupdocs.markdown.examples.developerguide.basicusage.convert.exportspreadsheet.ExportSpreadsheetInstance::run);
        EXAMPLES.put("LoadPasswordStatic", com.groupdocs.markdown.examples.developerguide.advancedusage.loading.loadapasswordprotecteddocument.LoadPasswordStatic::run);
        EXAMPLES.put("LoadPasswordInstance", com.groupdocs.markdown.examples.developerguide.advancedusage.loading.loadapasswordprotecteddocument.LoadPasswordInstance::run);
        EXAMPLES.put("LoadPasswordException", com.groupdocs.markdown.examples.developerguide.advancedusage.loading.loadapasswordprotecteddocument.LoadPasswordException::run);
        EXAMPLES.put("ExportEbookStatic", com.groupdocs.markdown.examples.developerguide.basicusage.convert.exportebook.ExportEbookStatic::run);
        EXAMPLES.put("ExportEbookInstance", com.groupdocs.markdown.examples.developerguide.basicusage.convert.exportebook.ExportEbookInstance::run);
        EXAMPLES.put("ExportTextStatic", com.groupdocs.markdown.examples.developerguide.basicusage.convert.exporttext.ExportTextStatic::run);
        EXAMPLES.put("ExportTextInstance", com.groupdocs.markdown.examples.developerguide.basicusage.convert.exporttext.ExportTextInstance::run);
        EXAMPLES.put("FlavorGfm", com.groupdocs.markdown.examples.developerguide.advancedusage.markdownflavor.FlavorGfm::run);
        EXAMPLES.put("FlavorCommonmark", com.groupdocs.markdown.examples.developerguide.advancedusage.markdownflavor.FlavorCommonmark::run);
        EXAMPLES.put("SpecificPagesStatic", com.groupdocs.markdown.examples.developerguide.advancedusage.convertspecificpages.SpecificPagesStatic::run);
        EXAMPLES.put("SpecificPagesInstance", com.groupdocs.markdown.examples.developerguide.advancedusage.convertspecificpages.SpecificPagesInstance::run);
        EXAMPLES.put("SpecificPagesFile", com.groupdocs.markdown.examples.developerguide.advancedusage.convertspecificpages.SpecificPagesFile::run);
        EXAMPLES.put("FrontMatterExample", com.groupdocs.markdown.examples.developerguide.advancedusage.frontmatter.FrontMatterExample::run);
        EXAMPLES.put("FrontMatterCombined", com.groupdocs.markdown.examples.developerguide.advancedusage.frontmatter.FrontMatterCombined::run);
        EXAMPLES.put("HeadingOffsetExample", com.groupdocs.markdown.examples.developerguide.advancedusage.headingoffset.HeadingOffsetExample::run);
        EXAMPLES.put("SpreadsheetTruncation", com.groupdocs.markdown.examples.developerguide.advancedusage.spreadsheetoptions.SpreadsheetTruncation::run);
        EXAMPLES.put("SpreadsheetSheets", com.groupdocs.markdown.examples.developerguide.advancedusage.spreadsheetoptions.SpreadsheetSheets::run);
        EXAMPLES.put("ErrorHandlingExample", com.groupdocs.markdown.examples.developerguide.advancedusage.errorhandling.ErrorHandlingExample::run);
        EXAMPLES.put("WarningsExample", com.groupdocs.markdown.examples.developerguide.advancedusage.errorhandling.WarningsExample::run);
        EXAMPLES.put("AsyncStatic", com.groupdocs.markdown.examples.developerguide.advancedusage.asyncapi.AsyncStatic::run);
        EXAMPLES.put("AsyncConcurrent", com.groupdocs.markdown.examples.developerguide.advancedusage.asyncapi.AsyncConcurrent::run);
        EXAMPLES.put("AsyncCancellation", com.groupdocs.markdown.examples.developerguide.advancedusage.asyncapi.AsyncCancellation::run);
        EXAMPLES.put("RagBasic", com.groupdocs.markdown.examples.developerguide.usecases.convertforrag.RagBasic::run);
        EXAMPLES.put("RagBatch", com.groupdocs.markdown.examples.developerguide.usecases.convertforrag.RagBatch::run);
        EXAMPLES.put("SsgExample", com.groupdocs.markdown.examples.developerguide.usecases.staticsitegenerator.SsgExample::run);
        EXAMPLES.put("SsgBatchHugo", com.groupdocs.markdown.examples.developerguide.usecases.staticsitegenerator.SsgBatchHugo::run);
        EXAMPLES.put("BatchBasic", com.groupdocs.markdown.examples.developerguide.usecases.batchconvert.BatchBasic::run);
        EXAMPLES.put("BatchAsync", com.groupdocs.markdown.examples.developerguide.usecases.batchconvert.BatchAsync::run);
        EXAMPLES.put("Base64Static", com.groupdocs.markdown.examples.developerguide.advancedusage.strategy.asbase64strategy.Base64Static::run);
        EXAMPLES.put("Base64Explicit", com.groupdocs.markdown.examples.developerguide.advancedusage.strategy.asbase64strategy.Base64Explicit::run);
        EXAMPLES.put("ImageFileBasic", com.groupdocs.markdown.examples.developerguide.advancedusage.strategy.imagefilestrategy.ImageFileBasic::run);
        EXAMPLES.put("ImageFileRelative", com.groupdocs.markdown.examples.developerguide.advancedusage.strategy.imagefilestrategy.ImageFileRelative::run);
        EXAMPLES.put("SkipImagesStatic", com.groupdocs.markdown.examples.developerguide.advancedusage.strategy.imageskipstrategy.SkipImagesStatic::run);
        EXAMPLES.put("SkipImagesInstance", com.groupdocs.markdown.examples.developerguide.advancedusage.strategy.imageskipstrategy.SkipImagesInstance::run);
        EXAMPLES.put("CustomStrategyRename", com.groupdocs.markdown.examples.developerguide.advancedusage.strategy.customstrategy.CustomStrategyRename::run);
        EXAMPLES.put("CustomStrategyReplace", com.groupdocs.markdown.examples.developerguide.advancedusage.strategy.customstrategy.CustomStrategyReplace::run);
        EXAMPLES.put("QuickExample", com.groupdocs.markdown.examples.productoverview.QuickExample::run);
    }

    public static void main(String[] args) throws Exception {
        if (args.length >= 1 && args[0].equals("--list")) {
            for (String name : EXAMPLES.keySet()) System.out.println(name);
            return;
        }

        if (args.length >= 2 && args[0].equals("--example")) {
            setLicense();
            Example example = EXAMPLES.get(args[1]);
            if (example == null) {
                System.err.println("Unknown example: " + args[1]);
                System.exit(1);
                return;
            }
            example.run();
            return;
        }

        setLicense();
        printIntro();
        int ok = 0, failed = 0;
        for (Map.Entry<String, Example> entry : EXAMPLES.entrySet()) {
            System.out.println("Running " + entry.getKey() + "...");
            try {
                entry.getValue().run();
                System.out.println("  Completed " + entry.getKey());
                ok++;
            } catch (Throwable t) {
                System.out.println("  Error: " + t.getMessage());
                failed++;
            }
        }
        System.out.println();
        System.out.println("Done. " + ok + " succeeded, " + failed + " failed.");
    }

    private static void printIntro() {
        System.out.println();
        System.out.println("=================================================================");
        System.out.println("  GroupDocs.Markdown for Java Examples");
        System.out.println("=================================================================");
        System.out.println();
    }

    private static void setLicense() {
        String licensePath = System.getenv("GROUPDOCS_LIC_PATH");
        if (licensePath == null || licensePath.isEmpty()) {
            File[] here = new File(".").listFiles();
            if (here != null) {
                for (File f : here) {
                    if (f.getName().endsWith(".lic")) { licensePath = f.getPath(); break; }
                }
            }
        }
        if (licensePath == null || !new File(licensePath).exists()) {
            return;  // evaluation mode; stay quiet so captured output stays clean
        }
        // Some product License.setLicense() implementations print debug lines to
        // stdout; silence stdout across the licensing loop so none of it can leak
        // into an example's captured output.
        java.io.PrintStream original = System.out;
        System.setOut(new java.io.PrintStream(new java.io.ByteArrayOutputStream()));
        try {
        try { new com.groupdocs.markdown.License().setLicense(licensePath); } catch (Throwable t) { /* product not present or not separately licensed */ }
        } finally {
            System.setOut(original);
        }
    }
}
